apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  containers:
  - name: simple-app-container
    image: ablankz/myapp:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-app
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - public-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: simple-app.default.svc.cluster.local
        port:
          number: 80
