prometheus:
  retention: "1h" # データの保持期間を1時間に設定
  retentionSize: "2GB" # ディスク使用量が2GBを超えると古いデータを削除
  podMonitorSelector: {}
  podMonitorSelectorNilUsesHelmValues: false
  ruleSelector: {}
  ruleSelectorNilUsesHelmValues: false
  serviceMonitorSelector: {}
  serviceMonitorSelectorNilUsesHelmValues: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: block-general
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 4Gi

grafana:
  enabled: false

alertmanager:
  enabled: false

prometheusOperator:
  enabled: true
  namespaces: ""
  denyNamespaces: ""
  prometheusInstanceNamespaces: ""
  alertmanagerInstanceNamespaces: ""
  thanosRulerInstanceNamespaces: ""
